const Images = {
  logo: require('./src/logo.png'),
  refer: require('./src/refer.png'),
  default: require('./src/default.png'),
  trophy: require('./src/trophy.png'),
  robot_setting: require('./src/robot-setting.gif'),
  update: require('./src/update.gif'),
  b1: require('./src/1.jpg'),
  b2: require('./src/2.jpg'),
  b3: require('./src/3.jpg'),
  b4: require('./src/4.jpg'),
  start: require('./src/start.jpg'),
  challenge: require('./src/challenge.png'),
  classic: require('./src/classic.png'),
  quick_mode: require('./src/quick-mode.png'),
  tournament: require('./src/tournament.png'),
  logoText: require('./src/logo-text.png'),
  crown: require('./src/crown.png'),
  G1: require('./src/1.png'),
  G2: require('./src/2.png'),
  G3: require('./src/3.png'),
  G4: require('./src/4.png'),
}

export default Images
